# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 101a0c0007ee870e63c506d2ed0ca4785fa84e3c28cda100542e99e1441d6fad4ad9edf18b955d305c7046d1ea2760865288cb1b92daeec79dbd1f3ccfb2d35d

test:
  secret_key_base: 908b94c5a5caaa39827cbd1b7d3a3f1bdc3f88772d751d762fb4f0269b4905952c76748de2fdf0e97c0b93d38a9debd3b2792ea66ef25768e6b434ed35eab70b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
